### ISSUE TITLE
gradle dependency / jcenter or maven central

### ISSUE THREAD

**Issue by mg6maciej** [splatte/gradle-android-appiconoverlay#1]
Hey,
I really like the idea (and I happen to know @krzysztofzablocki).
Would it be possible for you to upload this artifact to maven central or https://bintray.com/bintray/jcenter, so devs can easily integrate it without having to build it themselves?
Cheers,
Maciej

**Comment by splatte** [comment]
Hey, this was on my list too. Thanks for raising the issue here and pointing me to jcenter. I already signed up and it seems easy to get it up there. That should make it super simple to drop appiconoverlay into projects. Cheers!

**Comment by splatte** [comment]
The plugin is included in jcenter now. I was able to retrieve the jar from there by simply adding the dependency, very cool! I also updated the code to be compatible with version 1.0+ of the gradle android plugin. Let me know whether it works for you too.

**Comment by mg6maciej** [comment]
Works great for flavorless app.

I only had to install imagemagic with `sudo apt-get install imagemagick`. Might be worth mentioning how to do that on every plaform (except for Windows of course).

To make it work with flavors, I think you need to change overlayicon task name to

```
"${TASK_NAME}${variant.name}"
```
