### ISSUE TITLE
support builds with flavors

### ISSUE THREAD

**Issue by splatte** [splatte/gradle-android-appiconoverlay#2]
@mg6maciej in #1:

> Works great for flavorless app. [...]
> To make it work with flavors, I think you need to change overlayicon task name to
> `"${TASK_NAME}${variant.name}"`

**Comment by splatte** [comment]
thanks for the pointer, @mg6maciej, works great!

**Comment by mg6maciej** [comment]
I'll add it to my project when I'm back at work. Thanks!

**Comment by mg6maciej** [comment]
Works well. Thanks again.
